### ISSUE TITLE
i do node app.js to run the bot but

### ISSUE THREAD

**Issue by PlushBanshee** [TheEssemCraft/esmBot#2]
it quits after it says how many servers its in and then goes offline help!!!

**Comment by TheEssem** [comment]
Does it throw an error? Is it connected to a bot account? Is the bot account on any servers? I need some more info to try and find the solution.

**Comment by PlushBanshee** [comment]
the bot starts and then says loading commands then just jumps off line and go back to terminal

**Comment by TheEssem** [comment]
Huh, did you install the required dependencies using `npm install` inside of the directory?

**Comment by PlushBanshee** [comment]
i do a fresh install and let you know if it comes up again

**Comment by PlushBanshee** [comment]
okay it says ready to server 189 users in 2 servers
then go back to pi@raspberrypi 
Now before you say its the pi i trid doing sudo npm install on ubuntu and it just gives off errors all over so this is the closest to running the bot on the pi but if you know how to help fix the ubuntu problem you be my savor but yer 

pi 
LOG loading commands xxxxx.js
READY [READY] BOT ready to server 189 users in 2 servers
pi@raspberrypi:~/esmBot $

**Comment by TheEssem** [comment]
Have you tried running `npm install` without sudo? With commands like that, sudo is unnecessary, unless you're installing it globally, which the install script doesn't do by default.

**Comment by PlushBanshee** [comment]
yep i did sudo and errors everywhere espesh with discord.js trying to install 
i even did sudo su then sudo npm install on my ubuntu
i paste a error log

**Comment by PlushBanshee** [comment]
https://i.imgur.com/ZsEYH4U.png

**Comment by TheEssem** [comment]
Seems that the root account doesn't have the right permissions to access the .git directory. To fix this, just run `npm install` *without* using sudo.

**Comment by PlushBanshee** [comment]
tried that, that's why i started to use sudo i even did a fresh install of the newest Ubuntu and re-download all the requirements

**Comment by TheEssem** [comment]
The Node/NPM versions in the Ubuntu repos tend to be extremely outdated, use the Nodesource repos instead: https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions

**Comment by PlushBanshee** [comment]
![virtualbox_bskfvq62hr](https://user-images.githubusercontent.com/31914937/52019029-9df93380-2540-11e9-82f9-03c3d24b62cc.png)

**Comment by PlushBanshee** [comment]
then after i run npm install
~~~~~~~~~~~~~~~~~~~~~~~
banshee@PlushBanshee:~/esmBot$ npm install
npm ERR! path /home/banshee/.npm/_logs/2019-01-29T08_25_29_014Z-debug.log
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall unlink
npm ERR! Error: EACCES: permission denied, unlink '/home/banshee/.npm/_logs/2019-01-29T08_25_29_014Z-debug.log'
npm ERR!     at Object.fs.unlinkSync (fs.js:1061:18)
npm ERR!     at Function.rimrafSync [as sync] (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:306:17)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/npm.js:333:20
npm ERR!     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm ERR!     at Glob.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:151:7)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at Glob.emit (events.js:211:7)
npm ERR!     at Glob._finish (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:197:8)
npm ERR!     at done (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:182:14)
npm ERR!     at Glob._processReaddir2 (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:434:12)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:371:17
npm ERR!     at RES (/usr/local/lib/node_modules/npm/node_modules/inflight/inflight.js:31:16)
npm ERR!     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm ERR!     at Glob._readdirEntries (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:578:10)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:555:12
npm ERR!     at go$readdir$cb (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:162:14)
npm ERR!  { Error: EACCES: permission denied, unlink '/home/banshee/.npm/_logs/2019-01-29T08_25_29_014Z-debug.log'
npm ERR!     at Object.fs.unlinkSync (fs.js:1061:18)
npm ERR!     at Function.rimrafSync [as sync] (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:306:17)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/npm.js:333:20
npm ERR!     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm ERR!     at Glob.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:151:7)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at Glob.emit (events.js:211:7)
npm ERR!     at Glob._finish (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:197:8)
npm ERR!     at done (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:182:14)
npm ERR!     at Glob._processReaddir2 (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:434:12)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:371:17
npm ERR!     at RES (/usr/local/lib/node_modules/npm/node_modules/inflight/inflight.js:31:16)
npm ERR!     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm ERR!     at Glob._readdirEntries (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:578:10)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:555:12
npm ERR!     at go$readdir$cb (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:162:14)
npm ERR!   stack: 'Error: EACCES: permission denied, unlink \'/home/banshee/.npm/_logs/2019-01-29T08_25_29_014Z-debug.log\'\n    at Object.fs.unlinkSync (fs.js:1061:18)\n    at Function.rimrafSync [as sync] (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:306:17)\n    at /usr/local/lib/node_modules/npm/lib/npm.js:333:20\n    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)\n    at Glob.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:151:7)\n    at emitOne (events.js:116:13)\n    at Glob.emit (events.js:211:7)\n    at Glob._finish (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:197:8)\n    at done (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:182:14)\n    at Glob._processReaddir2 (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:434:12)\n    at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:371:17\n    at RES (/usr/local/lib/node_modules/npm/node_modules/inflight/inflight.js:31:16)\n    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)\n    at Glob._readdirEntries (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:578:10)\n    at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:555:12\n    at go$readdir$cb (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:162:14)',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'unlink',
npm ERR!   path: '/home/banshee/.npm/_logs/2019-01-29T08_25_29_014Z-debug.log' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

**Comment by PlushBanshee** [comment]
and this is sudo npm install
~~~~~~~~~~~~~~~~
banshee@PlushBanshee:~/esmBot$ sudo npm install
[sudo] password for banshee: 
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/which-dfa08158/package.json'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/which-dfa08158/README.md'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/which-dfa08158/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/optimist-a5695e9a/example/bool.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/wordwrap-ada1784b/example/center.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/window-or-global-113e34a6/lib/index.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/which-dfa08158/which.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/optimist-a5695e9a/example/default_singles.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/wordwrap-ada1784b/example/meat.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/optimist-a5695e9a/example/divide.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/gm-ccf64e82/lib/convenience/autoOrient.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/optimist-a5695e9a/example/line_count.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/gm-ccf64e82/lib/convenience/morph.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/optimist-a5695e9a/example/default_hash.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/qrcode-4d7b458d/build/qrcode.tosjis.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/gm-ccf64e82/lib/convenience/sepia.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/optimist-a5695e9a/example/line_count_wrap.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/acorn-6c847aa5/dist/acorn.mjs'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/gm-ccf64e82/lib/convenience/thumb.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/@discordjs/uws-99f913f4/uws_darwin_51.node'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/optimist-a5695e9a/example/nonopt.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/gm-ccf64e82/Makefile'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/optimist-a5695e9a/example/reflect.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/zlib-sync-ebd40f10/deps/zlib/deflate.h'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/optimist-a5695e9a/example/short.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/optimist-a5695e9a/example/string.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/zlib-sync-ebd40f10/deps/zlib/gzclose.c'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/optimist-a5695e9a/example/boolean_single.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/zlib-sync-ebd40f10/deps/zlib/gzguts.h'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/bufferutil-ff189c2b/prebuilds/win32-ia32/node-napi.node'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/optimist-a5695e9a/example/usage-options.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/optimist-a5695e9a/example/boolean_double.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/zlib-sync-ebd40f10/deps/zlib/gzlib.c'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/moment-duration-format-b8863835/test/vendor/moment.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/optimist-a5695e9a/example/xup.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/optimist-a5695e9a/example/line_count_options.js'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/zlib-sync-ebd40f10/deps/zlib/gzread.c'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/optimist-a5695e9a/readme.markdown'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/mocha-3bcebf43/README.md'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/zlib-sync-ebd40f10/deps/zlib/gzwrite.c'
npm WARN tar ENOENT: no such file or directory, open '/home/banshee/esmBot/node_modules/.staging/zlib-sync-ebd40f10/deps/zlib/infback.c'
npm ERR! err.code.match is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/banshee/.npm/_logs/2019-01-30T23_13_44_068Z-debug.log

**Comment by PlushBanshee** [comment]
banshee@PlushBanshee:~/esmBot$ node app.js
[2019-01-31 10:16:23]: ERROR Uncaught Exception: Error: Cannot find module 'better-sqlite-pool'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at new Enmap (/home/banshee/node_modules/enmap/src/index.js:94:24)
    at Object.<anonymous> (/home/banshee/esmBot/app.js:18:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

**Comment by PlushBanshee** [comment]
sorry if im getting in the way but i really like how you built this bot it has imagemagic in it and you one seems like the most advance bot on github that has this power of commands

**Comment by TheEssem** [comment]
```
curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
```

Run that to install the repos for the newest versions of Node.js, and then do `sudo apt-get install -y nodejs` as normal. You can't get the latest versions of Node without running that command.

**Comment by PlushBanshee** [comment]
banshee@PlushBanshee:~/esmBot$ node app.js
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: 0x9518b0 node::Abort() [node]
 2: 0x9525f9 node::OnFatalError(char const*, char const*) [node]
 3: 0xb28a0a v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: 0x7f387aea2f79 Require(v8::Local<v8::Object>, char const*) [/home/banshee/esmBot/node_modules/better-sqlite3/build/better_sqlite3.node]
 5: 0x7f387aea33ae Integer::Init(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Object>) [/home/banshee/esmBot/node_modules/better-sqlite3/build/better_sqlite3.node]
 6: 0x7f387aeab277 RegisterModule(v8::Local<v8::Object>, v8::Local<v8::Object>) [/home/banshee/esmBot/node_modules/better-sqlite3/build/better_sqlite3.node]
 7: 0x930a63  [node]
 8: 0x931050 node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [node]
 9: 0xbafa1a  [node]
10: 0xbb05c9 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
11: 0x383fc5ccfc5d 
Aborted (core dumped)
